CC=gcc
CFLAGS=-Wall
ARCHITECTURE=TEST_UNITAIRE

$(shell mkdir -p $(ARCHITECTURE))

EXEC=TestUnitaire

SRC= TestUnitaireMain.c

OBJ= $(SRC:.c=.o)

all: $(EXEC)

$(EXEC): $(OBJ)
	cd $(ARCHITECTURE) ; $(CC) -o $@ $^ ; cd .. ; ln -f -s $(ARCHITECTURE)/$(EXEC)

$(EXEC).o: $(INC)

%.o: %.c
	$(CC) -o $(ARCHITECTURE)/$@ -c $< $(CFLAGS)

clean:
	rm -f $(ARCHITECTURE)/*.o
	rm -f $(ARCHITECTURE)/$(EXEC)
	rm -f $(EXEC)
