EXECUTABLE = PokemonMaster

LIBS	= -lDataBase -lTools $(LIBX)

SRCS	= keyboard.c menu.c usecases.c pokemonMaster.c

OBJS  = $(SRCS:.c=.o)

allbin: all

include $(FOLDER_PROJECT)/src/Makefiles/Makefile.exe
