ARCHITECTURE = LINUX_GCC

LIBX        = -lm
LDFLAGS_EXE = -g -Wall
LIBPATH	    = -L$(FOLDER_EXPORT_LIB)
CPATH	      = -I$(FOLDER_EXPORT_INCLUDE)
CFLAGS		  = -std=gnu99 $(CPATH)

CMD_ECHO    = /bin/echo -e
CC          = /usr/bin/gcc
