all: lib

include $(FOLDER_PROJECT)/src/Makefiles/Makefile.master

LIBFILE = lib$(LIBNAME).a

lib:
	@$(MAKE) exportLib
	@$(MAKE) exportInclude

$(LIBFILE): $(OBJS)
	@$(CMD_ECHO) Creating archive $(LIBFILE) ... \\c
	@rm -f $(ARCHITECTURE)/$(LIBFILE)
	@cd $(ARCHITECTURE) ; ar cr $(LIBFILE) $(OBJS)
	@cd $(ARCHITECTURE) ; ranlib $(LIBFILE)
	@$(CMD_ECHO) done

exportLib: $(LIBFILE)
	@mkdir -p $(FOLDER_EXPORT_LIB)
	@$(CMD_ECHO) Exporting $(LIBFILE) ... \\c
	@rm -f $(FOLDER_EXPORT_LIB)/$(LIBFILE)
	@ln -f -s `pwd`/$(ARCHITECTURE)/$(LIBFILE) $(FOLDER_EXPORT_LIB)/
	@$(CMD_ECHO) done
