CREATE TABLE Group (id PRIMARY_KEY, name VARCHAR[25])
INSERT INTO Group VALUES ("Monstrueux")
INSERT INTO Group VALUES ("Aquatique 1")
INSERT INTO Group VALUES ("Insectoïde")
INSERT INTO Group VALUES ("Aérien")
INSERT INTO Group VALUES ("Terrestre")
INSERT INTO Group VALUES ("Féerique")
INSERT INTO Group VALUES ("Végétal")
INSERT INTO Group VALUES ("Humanoïde")
INSERT INTO Group VALUES ("Aquatique 3")
INSERT INTO Group VALUES ("Minéral")
INSERT INTO Group VALUES ("Amorphe")
INSERT INTO Group VALUES ("Aquatique 2")
INSERT INTO Group VALUES ("Métamorph")
INSERT INTO Group VALUES ("Draconique")
INSERT INTO Group VALUES ("Inconnu")
